
#include "bgfx_compute.sh"

IMAGE2D_WR(InputTexture, rgba32f, 0);
BUFFER_RW(_VelocityIn, vec2, 1);

uniform vec2 _Size;

NUM_THREADS(16, 16, 1)
void main()
{
    if (gl_GlobalInvocationID.x >= _Size.x || gl_GlobalInvocationID.y >= _Size.y)
    {
        return;
    }

	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    uint pos = gl_GlobalInvocationID.y * _Size.x + gl_GlobalInvocationID.x;
    imageStore(InputTexture, coord, vec4(_VelocityIn[pos].x, _VelocityIn[pos].y, 0 , 1));
}