#version 430

layout(rgba8) uniform writeonly image2D destTex;

layout(local_size_x = {{ NUM_THREADS }}, local_size_y = {{ NUM_THREADS }}, local_size_z = 1) in;

layout(std430, binding={{ PARTICLES_IN }}) buffer xst__ParticlesIn
{
    float _ParticlesIn[];
};

void main() {
    const ivec2 storePos = ivec2(gl_GlobalInvocationID.xy);
    const uint inPos = gl_GlobalInvocationID.y + gl_GlobalInvocationID.x;

    imageStore(destTex, storePos, vec4(_ParticlesIn[inPos], 0.0, 0.0, 0.0));
}