
#version 310 es

layout(local_size_x = {{ NUM_THREADS }}, local_size_y = {{ NUM_THREADS }}, local_size_z = 1) in;

uniform uvec2 _Size;

layout(std430, binding={{ GENERIC }}) buffer xst__Buffer
{
    vec2 _Buffer[];
};

void main()
{
    if (gl_GlobalInvocationID.x >= _Size.x || gl_GlobalInvocationID.y >= _Size.y)
    {
        return;
    }
    uint pos = gl_GlobalInvocationID.y * _Size.x + gl_GlobalInvocationID.x;
    _Buffer[pos].x = 0.0f;
}

